global:
  measurements:
    - name: podLatency
jobs:
  - name: pod-latency-test
    jobIterations: 10         # Create 50 objects
    qps: 20
    burst: 20
    namespace: benchmark
    podWait: true             # CRITICAL: Wait for pods to be ready
    objects:
      - objectTemplate: pod.yaml
        replicas: 1           # Create 1 replica of the template per iteration
